language: go

go:
  - 1.4

services:
  - riak

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/golang/protobuf/proto
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -cover
